#!/usr/bin/env bash
#
# Generate the MakerWorld multi-plate upload variant.
#
# MakerWorld's Parametric Model Maker exports a multi-plate 3MF by rendering
# each mw_plate_N() module as its own build plate — but it renders the script's
# top level into every one of those plates too. So the variant must (a) contain
# the plate-hook modules and (b) render nothing at the top level, while the
# normal desktop script must contain no hooks at all (uploading it to
# MakerWorld then just behaves as a classic single-output customizer script,
# STL download included).
#
# This script assembles the variant from the two sources of truth:
#   src/gridfinity_base.scad   (with the hidden mw_export switch flipped on,
#                               which silences the top-level render)
# + src/makerworld_hooks.scad  (the mw_plate_N / mw_assembly_view modules)
#
# Upload the generated file for the multi-plate listing. Note: MakerWorld
# disables STL download for multi-plate scripts (3MF only), so keep the
# regular src/gridfinity_base.scad published too if you want STL downloads —
# there, the Export plate parameter serves individual plates as STL.
#
# Usage:  ./make_makerworld.sh
set -euo pipefail
cd "$(dirname "$0")"

# MakerWorld names the customizer's downloaded 3MF after the uploaded .scad
# file, so the build output carries the product name.
NAME="3DMM Filament Zero Gridfinity Baseplates"

SRC="src/gridfinity_base.scad"
HOOKS="src/makerworld_hooks.scad"
OUT="build/$NAME.scad"
mkdir -p build

grep -q '^mw_export = false;$' "$SRC" || {
    echo "error: 'mw_export = false;' marker not found in $SRC" >&2
    exit 1
}
grep -q 'module mw_plate_36' "$HOOKS" || {
    echo "error: plate hooks not found in $HOOKS" >&2
    exit 1
}
if grep -q 'module mw_' "$SRC"; then
    echo "error: $SRC must not define mw_ modules (PMM renders the top level into every plate)" >&2
    exit 1
fi

{
    sed 's/^mw_export = false;$/mw_export = true;  \/\/ MakerWorld variant - generated by make_makerworld.sh/' "$SRC"
    echo
    cat "$HOOKS"
} > "$OUT"

echo "==> $OUT"
