#!/usr/bin/env bash
#
# Generate the MakerWorld upload variant of the parametric base.
#
# MakerWorld's Parametric Model Maker exports a multi-plate 3MF by calling the
# mw_plate_N() / mw_assembly_view() modules itself — the script must render
# nothing at the top level (see the official PMM syntax demo). The only
# difference from src/gridfinity_base.scad is the hidden mw_export switch, so
# this script just flips it rather than maintaining a second copy of the file.
#
# Upload build/gridfinity_base_makerworld.scad for the multi-plate listing.
# Note: MakerWorld disables STL download for multi-plate scripts, so keep the
# regular src/gridfinity_base.scad published too if you want STL downloads.
#
# Usage:  ./make_makerworld.sh
set -euo pipefail
cd "$(dirname "$0")"

SRC="src/gridfinity_base.scad"
OUT="build/gridfinity_base_makerworld.scad"
mkdir -p build

grep -q '^mw_export = false;$' "$SRC" || {
    echo "error: 'mw_export = false;' marker not found in $SRC" >&2
    exit 1
}

sed 's/^mw_export = false;$/mw_export = true;  \/\/ MakerWorld variant - generated by make_makerworld.sh/' \
    "$SRC" > "$OUT"

echo "==> $OUT"
